/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package act1;

import java.awt.CardLayout;

/**
 *
 * @author Pamela
 */
public class Welcome extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Welcome.class.getName());

    /**
     * Creates new form Main
     */
    CardLayout cl;
    public Welcome() {
        initComponents();
        cl = (CardLayout) Outlet.getLayout();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        DashboardButton = new javax.swing.JToggleButton();
        EmployeesButton = new javax.swing.JToggleButton();
        StudentsButton = new javax.swing.JToggleButton();
        Outlet = new javax.swing.JPanel();
        DashboardCard = new javax.swing.JPanel();
        Dashboard = new javax.swing.JLabel();
        EmployeesCard = new javax.swing.JPanel();
        Employees = new javax.swing.JLabel();
        StudentsCard = new javax.swing.JPanel();
        Students = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        DashboardButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        DashboardButton.setText("Dashboard");
        DashboardButton.setAlignmentY(2.0F);
        DashboardButton.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        DashboardButton.addActionListener(this::DashboardButtonActionPerformed);

        EmployeesButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        EmployeesButton.setText("Employees");
        EmployeesButton.setAlignmentY(2.0F);
        EmployeesButton.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        EmployeesButton.addActionListener(this::EmployeesButtonActionPerformed);

        StudentsButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        StudentsButton.setText("Students");
        StudentsButton.setAlignmentY(2.0F);
        StudentsButton.setCursor(new java.awt.Cursor(java.awt.Cursor.SE_RESIZE_CURSOR));
        StudentsButton.addActionListener(this::StudentsButtonActionPerformed);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(DashboardButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(EmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StudentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(DashboardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(EmployeesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(StudentsButton, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Outlet.setBackground(new java.awt.Color(255, 255, 255));
        Outlet.setLayout(new java.awt.CardLayout());

        DashboardCard.setBackground(new java.awt.Color(153, 153, 255));

        Dashboard.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Dashboard.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Dashboard.setText("Dashboard");

        javax.swing.GroupLayout DashboardCardLayout = new javax.swing.GroupLayout(DashboardCard);
        DashboardCard.setLayout(DashboardCardLayout);
        DashboardCardLayout.setHorizontalGroup(
            DashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(DashboardCardLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Dashboard, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        DashboardCardLayout.setVerticalGroup(
            DashboardCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, DashboardCardLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(Dashboard)
                .addGap(154, 154, 154))
        );

        Outlet.add(DashboardCard, "Dashboard");

        EmployeesCard.setBackground(new java.awt.Color(255, 51, 51));

        Employees.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Employees.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Employees.setText("Employees");

        javax.swing.GroupLayout EmployeesCardLayout = new javax.swing.GroupLayout(EmployeesCard);
        EmployeesCard.setLayout(EmployeesCardLayout);
        EmployeesCardLayout.setHorizontalGroup(
            EmployeesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeesCardLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Employees, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        EmployeesCardLayout.setVerticalGroup(
            EmployeesCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeesCardLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(Employees)
                .addGap(154, 154, 154))
        );

        Outlet.add(EmployeesCard, "Employees");

        StudentsCard.setBackground(new java.awt.Color(255, 255, 153));

        Students.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        Students.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Students.setText("Students");

        javax.swing.GroupLayout StudentsCardLayout = new javax.swing.GroupLayout(StudentsCard);
        StudentsCard.setLayout(StudentsCardLayout);
        StudentsCardLayout.setHorizontalGroup(
            StudentsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(StudentsCardLayout.createSequentialGroup()
                .addGap(87, 87, 87)
                .addComponent(Students, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(92, Short.MAX_VALUE))
        );
        StudentsCardLayout.setVerticalGroup(
            StudentsCardLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, StudentsCardLayout.createSequentialGroup()
                .addContainerGap(174, Short.MAX_VALUE)
                .addComponent(Students)
                .addGap(154, 154, 154))
        );

        Outlet.add(StudentsCard, "Students");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Outlet, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Outlet, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void DashboardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DashboardButtonActionPerformed

        cl.show(Outlet, "Dashboard");
    }//GEN-LAST:event_DashboardButtonActionPerformed

    private void EmployeesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmployeesButtonActionPerformed
        // TODO add your handling code here:
        cl.show(Outlet, "Employees");
        
    }//GEN-LAST:event_EmployeesButtonActionPerformed

    private void StudentsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StudentsButtonActionPerformed
        // TODO add your handling code here:
        cl.show(Outlet, "Students");
    }//GEN-LAST:event_StudentsButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Welcome().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Dashboard;
    private javax.swing.JToggleButton DashboardButton;
    private javax.swing.JPanel DashboardCard;
    private javax.swing.JLabel Employees;
    private javax.swing.JToggleButton EmployeesButton;
    private javax.swing.JPanel EmployeesCard;
    private javax.swing.JPanel Outlet;
    private javax.swing.JLabel Students;
    private javax.swing.JToggleButton StudentsButton;
    private javax.swing.JPanel StudentsCard;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
